### ISSUE TITLE
SSLHandshakeException on Kind and OVH K8s

### ISSUE THREAD

**Issue by geraldpereira** [OctoPerf/kraken#57]
```
io.kubernetes.client.openapi.ApiException: javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:898)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Handler com.kraken.ap#a(String) [DispatcherHandler]
	|_ checkpoint ⇢ HTTP GET "/task/list" [ExceptionHandlingWebHandler]
Stack trace:
		at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:898)
		at io.kubernetes.client.openapi.apis.CoreV1Api.listNamespacedPodWithHttpInfo(CoreV1Api.java:17190)
		at io.kubernetes.client.openapi.apis.CoreV1Api.listNamespacedPod(CoreV1Api.java:17161)
		at com.kraken.u.lambda$list$7(u.java)
```

**Comment by geraldpereira** [comment]
https://github.com/golang/go/issues/35722#issuecomment-566206339

Try to update the openJDK version.
